version: "3.5"
services:
  influx:
    image: influxdb:latest
    container_name: influxdb
    ports:
      -  "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=root
      - DOCKER_INFLUXDB_INIT_PASSWORD=root1234
      - DOCKER_INFLUXDB_INIT_ORG=reporting
      - DOCKER_INFLUXDB_INIT_BUCKET=reportingEvents
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=root
      - DOCKER_INFLUXDB_INIT_MODE=setup
